// Master Scope of Work template library — used to seed the ScopeTemplate entity.
// Selecting one of these in the Scope of Work form copies the values onto the
// individual scope; it never modifies these master templates.
export const SCOPE_TEMPLATES = [
  {
    name: 'General Maintenance Clean',
    service_type: 'general_maintenance_clean',
    description: 'Standard recurring maintenance clean for residential properties.',
    default_tasks_included: [
      'Dusting all accessible surfaces',
      'Vacuum and mop all floors',
      'Wipe down kitchen benchtops and splashback',
      'Clean and sanitise bathrooms (toilet, shower, basin)',
      'Empty bins and reline',
      'Make beds (linen supplied by client)',
      'Wipe mirrors and glass surfaces',
    ],
    default_addons: ['Inside oven clean', 'Inside fridge clean', 'Interior window cleaning', 'Load/unload dishwasher'],
    default_tasks_excluded: ['Exterior windows', 'Wall washing', 'Carpet steam cleaning', 'Heavy decluttering'],
    default_terms_conditions: 'Payment due within 7 days of invoice. Additional tasks outside this scope will be quoted separately. Please ensure clear access to the property at the scheduled time.',
  },
  {
    name: 'Detailed Refresh Clean',
    service_type: 'detailed_refresh_clean',
    description: 'A more thorough clean covering detail areas beyond a standard maintenance clean.',
    default_tasks_included: [
      'All General Maintenance Clean tasks',
      'Detailed dusting including skirting boards and light fittings',
      'Spot cleaning walls and doors',
      'Inside window sills and tracks',
      'Degreasing kitchen splashback',
      'Sanitising all high-touch points',
    ],
    default_addons: ['Balcony/patio clean', 'Blinds dusting', 'Inside cupboards (empty)'],
    default_tasks_excluded: ['Steam cleaning carpets', 'Exterior pressure washing'],
    default_terms_conditions: 'Payment due within 7 days of invoice. Additional tasks outside this scope will be quoted separately.',
  },
  {
    name: 'Deep or Spring Clean',
    service_type: 'deep_spring_clean',
    description: 'Full top-to-bottom deep clean for periodic refresh or seasonal reset.',
    default_tasks_included: [
      'Full property deep clean',
      'Inside oven and stovetop',
      'Inside fridge and freezer',
      'Inside all cupboards and drawers',
      'Detailed bathroom degrease and descale',
      'Skirting boards, light switches, door frames',
      'Wall spot cleaning',
      'Extractor fan and range hood clean',
    ],
    default_addons: ['Carpet steam cleaning', 'Exterior window cleaning', 'Garage clean-out', 'Full wall washing'],
    default_tasks_excluded: ['Pest control', 'Structural repairs', 'Exterior pressure washing (quoted separately)'],
    default_terms_conditions: 'Payment due within 7 days of invoice. Quoted hours are an estimate — properties in extreme condition may incur additional charges, agreed with the client beforehand.',
  },
  {
    name: 'Office and Commercial Cleaning',
    service_type: 'office_commercial_cleaning',
    description: 'Recurring commercial servicing for offices and small business premises.',
    default_tasks_included: [
      'Vacuum and mop all floors',
      'Empty and reline all bins',
      'Wipe down desks and communal surfaces',
      'Clean and sanitise kitchenette',
      'Clean and restock bathrooms',
      'Dust surfaces and skirting boards',
      'Glass door and partition cleaning',
    ],
    default_addons: ['Carpet spot treatment', 'Window cleaning', 'Fridge/microwave clean', 'After-hours servicing'],
    default_tasks_excluded: ['IT equipment cleaning', 'Server room access', 'Exterior building cleaning'],
    default_terms_conditions: 'Payment terms as per commercial servicing agreement. Recurring visits billed per agreed schedule. Access arrangements to be confirmed with site contact.',
  },
  {
    name: 'Airbnb and Short-Stay Cleaning',
    service_type: 'airbnb_shortstay_cleaning',
    description: 'Guest changeover cleaning for short-stay and Airbnb properties.',
    default_tasks_included: [
      'Full changeover clean between guests',
      'Strip and remake beds with fresh linen',
      'Kitchen and bathroom sanitising',
      'Restocking of guest essentials (supplied by host)',
      'Rubbish removal',
      'Vacuum and mop throughout',
      'Final presentation check (staging, towels folded)',
    ],
    default_addons: ['Linen laundry service', 'Same-day turnaround', 'Welcome basket set-up'],
    default_tasks_excluded: ['Guest damage repairs', 'Maintenance issues', 'Linen supply (unless arranged)'],
    default_terms_conditions: 'Payment due on invoice as per booking agreement. Same-day turnarounds must be confirmed in advance to guarantee availability.',
  },
  {
    name: 'Move-In Cleaning',
    service_type: 'move_in_cleaning',
    description: 'Full clean of an empty property ahead of moving in.',
    default_tasks_included: [
      'Full empty-property clean',
      'Inside all cupboards, wardrobes and drawers',
      'Kitchen degrease and sanitise',
      'Bathroom descale and sanitise',
      'Skirting boards, light switches, door frames',
      'Vacuum and mop all floors',
    ],
    default_addons: ['Inside oven clean', 'Carpet steam cleaning', 'Wall washing'],
    default_tasks_excluded: ['Rubbish/furniture removal', 'Repairs or touch-up painting'],
    default_terms_conditions: 'Payment due within 7 days of invoice. Property must be empty of furniture/belongings for full scope to be completed.',
  },
  {
    name: 'Rental Inspection Rescue',
    service_type: 'rental_inspection_rescue',
    description: 'Priority clean to prepare a rental property for an upcoming inspection.',
    default_tasks_included: [
      'Priority same/next-day service',
      'Full bond-clean style detailed clean',
      'Kitchen, bathroom and living areas detailed clean',
      'Skirting boards, tracks and vents',
      'Wall mark spot cleaning',
      'Inside oven and range hood',
    ],
    default_addons: ['Carpet steam cleaning', 'Exterior window cleaning', 'Garage/carport sweep'],
    default_tasks_excluded: ['Structural repairs', 'Pest treatment', 'Landlord-requested maintenance items'],
    default_terms_conditions: 'Payment due on completion given priority scheduling. Additional issues raised by the property manager outside this scope will be quoted separately.',
  },
  {
    name: 'Pre-Sale Presentation Cleaning',
    service_type: 'pre_sale_presentation_cleaning',
    description: 'Presentation clean ahead of open homes or property photography.',
    default_tasks_included: [
      'Full detailed clean for open home presentation',
      'Streak-free glass and mirrors',
      'Kitchen and bathroom detailing',
      'Floor care (vacuum/mop)',
      'Light surface tidy/declutter',
      'Skirting boards and light fittings',
    ],
    default_addons: ['Carpet steam cleaning', 'Exterior window cleaning', 'Entryway/driveway pressure wash'],
    default_tasks_excluded: ['Styling/staging furniture', 'Repairs', 'Garden/landscaping'],
    default_terms_conditions: 'Payment due within 7 days of invoice. Recommended to schedule 1–2 days prior to first open home.',
  },
  {
    name: 'Window Cleaning',
    service_type: 'window_cleaning',
    description: 'Interior and accessible exterior glass cleaning.',
    default_tasks_included: [
      'Interior glass cleaning',
      'Exterior glass cleaning (ground floor/accessible)',
      'Sills and tracks wiped down',
      'Flyscreens spot cleaned',
    ],
    default_addons: ['Second storey/high access windows', 'Flyscreen removal and wash', 'Sliding door track deep clean'],
    default_tasks_excluded: ['Window repairs', 'Broken glass replacement', 'Tinting'],
    default_terms_conditions: 'Payment due on completion. High-access windows require prior confirmation of safe access.',
  },
  {
    name: 'Pressure Washing',
    service_type: 'pressure_washing',
    description: 'Exterior pressure washing for driveways, paths and outdoor areas.',
    default_tasks_included: [
      'Driveway and pathway pressure wash',
      'Exterior entryway clean',
      'Patio/alfresco pressure wash',
      'Removal of surface dirt, moss and grime',
    ],
    default_addons: ['Roof pressure wash', 'Fence wash', 'Pool area surrounds'],
    default_tasks_excluded: ['Sealing/coating application', 'Structural repairs', 'Damage from pre-existing cracks'],
    default_terms_conditions: 'Payment due on completion. Weather-dependent — may be rescheduled in case of rain.',
  },
];